-- 建立数据库
CREATE DATABASE `FlagHead` DEFAULT charset=utf8;
USE `FlagHead`;

-- 建立微信头像小国旗数据表
DROP TABLE IF EXISTS `FlagHead`;
CREATE TABLE IF NOT EXISTS `FlagHead`(
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `wx` TEXT NOT NULL COMMENT 'json',
  `time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `status` TINYINT(1) NOT NULL DEFAULT '1' COMMENT '状态(单选):0=未激活,1=激活',
  PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='头像小国旗';